 # Generated by Django 5.0.6 on 2024-06-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('repeatpassword', models.CharField(max_length=10)),
            ],
        ),
    ]
